name: flutter_map_vector_tile
description: Vector tiles for flutter_map
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.1.1
  vector_map_tiles:
    git:
      url: https://github.com/greensopinion/flutter-vector-map-tiles.git

  http: ^1.1.0
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/testStyle.json
    - assets/data/streets.json
